# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 504164e6ea1b19909b616fe2b1c221957b34ed646b5a45bd2b41977e96bdd7457b8679790915aec6c7dc3e07eadfa0f63fc2e4bc0b1960db3e18c6894c3f0863

test:
  secret_key_base: 6e58ebc12450410e3aec0ecb7decafa3d55e3876c4189be5f9a269f63d2d11b34abbaf3fa9b0cc0f59ef0f98225c7f4394521185f1bd686a12f75eab117b4f98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
